export enum ShortCode {
	ASPECT_RATIO = 'a',
	BEZEL_COLOR = 'c',
	BEZEL_WIDTH = 'b',
	CURVED = 'u',
	DESK_HEIGHT = 'g',
	DESK_WIDTH = 'w',
	DIAGONAL = 'd',
	DISPLAY_TYPE = 'p',
	HDR = 'l',
	HORIZONTAL_RESOLUTION = 'h',
	NAME = 'm',
	OFFSET_X = 'x',
	OFFSET_Y = 'y',
	OFFSET_Z = 'q',
	ORIENTATION = 'o',
	REFRESH_RATE = 'r',
	RESOLUTION_STANDARD = 's',
	RESPONSE_TIME = 't',
	ROTATE_X = 'j',
	ROTATE_Y = 'k',
	SCALE = 'z',
	SETUP_ID = 'i',
	SETUP_NAME = 'f',
	SYNC_TYPE = 'n',
	VERTICAL_RESOLUTION = 'v',
}
